export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_LEARNING_UNIT = "SET_CURRENT_LEARNING_UNIT";
export const SET_ALL_LEARNING_UNITS_OF_SELECTED_MODULE = "SET_ALL_LEARNING_UNITS_OF_SELECTED_MODULE";
export const SET_CURRENT_MODULE = 'SET_CURRENT_MODULE';
